Repository Nolmung/Nolmung-client, pull requests merged in 2024-11, with the labels that each got.

#6 env/SV-195 : storyBook 설정
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .yarn/install-state.gz
  .yarnrc.yml
  package.json
  src/common/components/Button/Button.stories.tsx
  src/common/components/Button/Button.tsx
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: 🌱 env

#7 fix/SV-92: styled-components 의존성 수정 및 타입 정의 파일 추가
  package.json
  yarn.lock
Labels: 🔧fix, 🌱 env

#8 Feat/SV-107:공통컴포넌트(Header, TabBar, Layout) 구현 완료
  .yarn/install-state.gz
  package.json
  public/svgs/goBackIcon.svg
  public/svgs/tabBarCalenderIcon.svg
  public/svgs/tabBarCalenderIconActive.svg
  public/svgs/tabBarMapIcon.svg
  public/svgs/tabBarMapIconActive.svg
  public/svgs/tabBarMyIcon.svg
  public/svgs/tabBarMyIconActive.svg
  public/svgs/tabBarRecommendIcon.svg
  public/svgs/tabBarRecommendIconActive.svg
  src/App.tsx
  src/Router.tsx
  src/assets/ fonts/PretendardVariable.woff2
  src/assets/images/svgs/GoBackIcon.tsx
  src/assets/images/svgs/TabBarCalenderIcon.tsx
  src/assets/images/svgs/TabBarCalenderIconActive.tsx
  src/assets/images/svgs/TabBarMapIcon.tsx
  src/assets/images/svgs/TabBarMapIconActive.tsx
  src/assets/images/svgs/TabBarMyIcon.tsx
  src/assets/images/svgs/TabBarMyIconActive.tsx
  src/assets/images/svgs/TabBarRecommendIcon.tsx
  src/assets/images/svgs/TabBarRecommendIconActive.tsx
  src/assets/images/svgs/index.ts
  src/common/components/button/Button.stories.tsx
  src/common/components/button/Button.tsx
  src/common/components/header/index.stories.tsx
  src/common/components/header/index.styles.ts
  src/common/components/header/index.tsx
  src/common/components/header/index.type.ts
  src/common/components/layout/flex.ts
  src/common/components/layout/index.styles.ts
  src/common/components/layout/index.tsx
  src/common/components/layout/index.type.ts
  src/common/components/tabBar/index.stories.tsx
  src/common/components/tabBar/index.styles.ts
  src/common/components/tabBar/index.tsx
  src/common/components/tabBar/index.type.ts
  src/common/constants/tabBarItems.ts
  src/main.tsx
  src/styles/GlobalStyles.ts
  tsconfig.app.tsbuildinfo
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#9 feat/SV-180: 시설 상세페이지 UI 구현
  package.json
  public/svgs/AllKindDogAvailable.svg
  public/svgs/BackArrowBlack.svg
  public/svgs/BackArrowWhite.svg
  public/svgs/DogPaw.svg
  public/svgs/FilledStar.svg
  public/svgs/ParkAvailable.svg
  public/svgs/Phone.svg
  public/svgs/Price.svg
  public/svgs/Time.svg
  public/svgs/UnderTenKilos.svg
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/assets/images/svgs/AllKindDogAvailable.tsx
  src/assets/images/svgs/BackArrowBlack.tsx
  src/assets/images/svgs/BackArrowWhite.tsx
  src/assets/images/svgs/DogPaw.tsx
  src/assets/images/svgs/FilledStar.tsx
  src/assets/images/svgs/ParkAvailable.tsx
  src/assets/images/svgs/Phone.tsx
  src/assets/images/svgs/Price.tsx
  src/assets/images/svgs/Time.tsx
  src/assets/images/svgs/UnderTenKilos.tsx
  src/assets/images/svgs/index.ts
  src/common/components/header/index.stories.tsx
  src/common/components/header/index.tsx
  src/common/components/layout/flex.ts
  src/common/components/layout/index.styles.ts
  src/common/components/layout/index.tsx
  src/common/components/tabBar/index.styles.ts
  src/common/components/tabBar/index.tsx
  src/common/constants/route.ts
  src/index.css
  src/pages/detail/components/KeywordReview.tsx
  src/pages/detail/components/TodayMungCard.tsx
  src/pages/detail/hooks/useScrollTop.ts
  src/pages/detail/index.tsx
  src/pages/detail/styles/detail.styles.ts
  src/pages/detail/styles/keywordReview.style.ts
  src/pages/detail/styles/todayMung.style.ts
  yarn.lock
Labels: ✨ feat

#10 feat/SV-181: 상세페이지 Mock API 연동
  eslint.config.js
  package.json
  public/mockServiceWorker.js
  public/svgs/Under15Kilos.svg
  public/svgs/Under25Kilos.svg
  public/svgs/UnderTenKilos.svg
  src/App.tsx
  src/assets/images/svgs/Under15Kilos.tsx
  src/assets/images/svgs/Under25Kilos.tsx
  src/assets/images/svgs/index.ts
  src/common/components/layout/flex.ts
  src/common/components/layout/index.styles.ts
  src/common/constants/reviewLabels.ts
  src/common/types/index.ts
  src/common/utils/findKeywordById.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/data/postDetail.ts
  src/mocks/handler.ts
  src/mocks/mockApis/place.ts
  src/pages/detail/components/InfoIcons.tsx
  src/pages/detail/components/KeywordReview.tsx
  src/pages/detail/components/TodayMungCard.tsx
  src/pages/detail/index.tsx
  src/pages/detail/querys/index.ts
  src/pages/detail/styles/detail.styles.ts
  src/pages/detail/styles/keywordReview.style.ts
  src/pages/detail/styles/todayMung.style.ts
  src/pages/detail/styles/todayMungCard.style.ts
  src/service/apis/place/index.ts
  src/service/apis/place/index.type.ts
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ✨ feat

#11 feat/SV-114: 검색바 공통 컴포넌트 구현, 검색 페이지 및 최근 검색어 기능 구현
  public/svgs/CancelIcon.svg
  public/svgs/TimeRecord.svg
  public/svgs/search.svg
  src/Router.tsx
  src/assets/images/svgs/CancelIcon.tsx
  src/assets/images/svgs/Search.tsx
  src/assets/images/svgs/TimeRecord.tsx
  src/assets/images/svgs/index.ts
  src/common/components/button/Button.stories.tsx
  src/common/components/button/Button.style.ts
  src/common/components/button/Button.tsx
  src/common/components/button/Button.type.ts
  src/common/components/layout/index.tsx
  src/common/components/modal/index.stories.tsx
  src/common/components/modal/index.styles.ts
  src/common/components/modal/index.tsx
  src/common/components/modal/index.type.ts
  src/common/components/searchInput/index.stories.tsx
  src/common/components/searchInput/index.style.ts
  src/common/components/searchInput/index.tsx
  src/common/constants/route.ts
  src/common/hooks/useModal.ts
  src/index.css
  src/pages/search/components/NoSearchHistory.tsx
  src/pages/search/components/SearchHistoryList.tsx
  src/pages/search/index.tsx
  src/pages/search/styles/NoSearchHistory.style.ts
  src/pages/search/styles/index.style.ts
  src/pages/search/utils/searchUtils.ts
  src/styles/GlobalStyles.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#12 feat/SV-135: BottomSheet UI 및 인터렉션 구현
  src/common/constants/ui.ts
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/bottomSheet/Handle.tsx
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/hooks/useBottomSheet.ts
  src/pages/main/index.tsx
  src/pages/main/styles/BottomSheet.style.ts
  src/pages/main/styles/BottomSheetHandle.style.ts
  src/pages/main/styles/Content.style.ts
  src/pages/main/styles/index.style.ts
Labels: ✨ feat

#14 feat/SV-135: 데스크탑 환경에서도 bottomSheet가 움직이도록 구현
  src/common/components/searchInput/index.tsx
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/hooks/useMouseBottomSheet.ts
  src/pages/main/utils/checkUserDevice.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#17 feat/SV-199: bottomSheet Contet UI 구현
  src/mocks/data/placeMap.ts
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/styles/Content.style.ts
  src/service/apis/place/index.type.ts
Labels: ✨ feat

#15 feat/SV-18: 로그인 UI, 카카오로그인 구현, signUp 페이지 연결
  public/svgs/LoginBackgroundimg.png
  public/svgs/LoginBackgroundimg.svg
  public/svgs/NolmungLogo.svg
  src/Router.tsx
  src/assets/images/svgs/LoginBackgroundimg.tsx
  src/assets/images/svgs/NolmungLogo.tsx
  src/assets/images/svgs/index.ts
  src/common/components/layout/index.tsx
  src/common/constants/route.ts
  src/pages/login/components/KakaoLoginButton.tsx
  src/pages/login/index.tsx
  src/pages/login/styles/login.styles.ts
  src/pages/signUp/index.tsx
  src/styles/GlobalStyles.ts
Labels: ✨ feat

#13 feat/SV-70: 네이버 지도 API를 이용한 지도 UI 구현
  .gitignore
  index.html
  package.json
  public/svgs/amusementparkMarker.svg
  public/svgs/cafeIcon.svg
  public/svgs/cafeMarker.svg
  public/svgs/defaultMarker.svg
  public/svgs/foodMarker.svg
  public/svgs/galleryMarker.svg
  public/svgs/hotelMarker.svg
  public/svgs/museumMarker.svg
  public/svgs/playgroundMarker.svg
  public/svgs/refresh.svg
  public/svgs/travelMarker.svg
  src/assets/images/svgs/AmusementparkMarker.tsx
  src/assets/images/svgs/CafeIcon.tsx
  src/assets/images/svgs/CafeMarker.tsx
  src/assets/images/svgs/DefaultMarker.tsx
  src/assets/images/svgs/FoodMarker.tsx
  src/assets/images/svgs/GalleryMarker.tsx
  src/assets/images/svgs/HotelMarker.tsx
  src/assets/images/svgs/MuseumMarker.tsx
  src/assets/images/svgs/PlaygroundMarker.tsx
  src/assets/images/svgs/Refresh.tsx
  src/assets/images/svgs/TravelMarker.tsx
  src/assets/images/svgs/index.ts
  src/common/components/tabBar/index.styles.ts
  src/common/constants/categories.ts
  src/common/constants/defaultLatLng.ts
  src/common/types/index.ts
  src/mocks/data/markerData.ts
  src/pages/main/components/CustomMarker.tsx
  src/pages/main/hooks/useMapCenter.ts
  src/pages/main/index.tsx
  src/pages/main/styles/CustomMarker.styles.ts
  src/pages/main/styles/index.style.ts
  src/pages/main/types/index.ts
  src/pages/main/utils/coordinateUtils.ts
  src/pages/main/utils/markerUtils.tsx
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#20 fix/SV-135: 모달, 탭바, 카테고리바, 바텀시트 z-index 조절
  src/common/components/modal/index.styles.ts
  src/common/components/searchInput/index.tsx
  src/common/components/tabBar/index.styles.ts
  src/pages/main/components/categoryBar/index.tsx
  src/pages/main/styles/BottomSheet.style.ts
  src/pages/main/styles/CategoryBar.style.ts
  src/pages/main/styles/index.style.ts
Labels: 🔧fix

#21 fix/SV-135_2: 카테고리 선택 시 탭바 안 보이도록 수정
  src/common/components/layout/index.tsx
Labels: ✨ feat
