Repository Nolmung/Nolmung-client, pull requests merged in 2024-12, with the labels that each got.

#23 feat/SV-130: 오늘멍 작성 페이지 UI 구현
  public/pngs/TodayMungLogo.png
  public/svgs/CameraIcon.svg
  public/svgs/CheckEmptyGreen.svg
  public/svgs/CheckFiiledDark.svg
  public/svgs/PlusIcon.svg
  src/Router.tsx
  src/assets/images/svgs/CameraIcon.tsx
  src/assets/images/svgs/CheckEmptyGreen.tsx
  src/assets/images/svgs/CheckFiiledDark.tsx
  src/assets/images/svgs/PlusIcon.tsx
  src/assets/images/svgs/index.ts
  src/common/components/layout/index.tsx
  src/common/constants/route.ts
  src/common/constants/ui.ts
  src/pages/main/hooks/useBottomSheet.ts
  src/pages/todayMungPlaceRegist/index.tsx
  src/pages/todayMungWrite/components/DogCard.tsx
  src/pages/todayMungWrite/components/Editor.tsx
  src/pages/todayMungWrite/components/MediaGroup.tsx
  src/pages/todayMungWrite/components/VisitedPlaceCard.tsx
  src/pages/todayMungWrite/index.tsx
  src/pages/todayMungWrite/stores/reviewStore.ts
  src/pages/todayMungWrite/stores/todayMungStore.ts
  src/pages/todayMungWrite/styles/DogCard.style.ts
  src/pages/todayMungWrite/styles/Editor.style.ts
  src/pages/todayMungWrite/styles/MediaGroup.style.ts
  src/pages/todayMungWrite/styles/VisitedPlaceCard.style.ts
  src/pages/todayMungWrite/styles/index.style.ts
  src/service/apis/diary/index.type.ts
  src/service/apis/user/index.types.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#26 Feat/SV-84: 오늘멍 상세페이지 UI 구현
  .yarn/install-state.gz
  public/svgs/deleteIcon.svg
  public/svgs/dotdotdotIcon.svg
  public/svgs/editIcon.svg
  public/svgs/locationPinIcon.svg
  src/Router.tsx
  src/assets/images/svgs/DeleteIcon.tsx
  src/assets/images/svgs/DotdotdotIcon.tsx
  src/assets/images/svgs/EditIcon.tsx
  src/assets/images/svgs/LocationPinIcon.tsx
  src/assets/images/svgs/index.ts
  src/common/components/layout/index.tsx
  src/common/components/tabBar/index.tsx
  src/common/components/tabBar/utils/tabUtils.ts
  src/common/constants/route.ts
  src/mocks/data/todaymungDetailData.ts
  src/pages/todayMungDetail/components/dogTag/index.tsx
  src/pages/todayMungDetail/components/editButton/index.tsx
  src/pages/todayMungDetail/components/imageCard/index.tsx
  src/pages/todayMungDetail/components/placeTag/index.tsx
  src/pages/todayMungDetail/components/textContent/index.tsx
  src/pages/todayMungDetail/index.tsx
  src/pages/todayMungDetail/styles/DogTagCard.style.ts
  src/pages/todayMungDetail/styles/EditButton.style.ts
  src/pages/todayMungDetail/styles/ImageCard.style.ts
  src/pages/todayMungDetail/styles/PlaceTagCard.style.ts
  src/pages/todayMungDetail/styles/TextContent.style.ts
  src/pages/todayMungDetail/styles/index.style.ts
  src/pages/todayMungDetail/types/DiaryType.ts
  src/pages/todaymung/types/TodayMungList.type.ts
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ✨ feat

#27 feat/SV-98: 추천페이지 UI 구현
  src/Router.tsx
  src/common/components/layout/index.tsx
  src/common/constants/route.ts
  src/pages/main/hooks/useMapCenter.ts
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/recommend/index.tsx
  src/pages/recommend/styles/RecommendCard.style.ts
  src/pages/recommend/styles/index.style.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#28 feat/SV-162: 마이페이지 UI 구현
  public/svgs/heartIcon.svg
  public/svgs/logoutIcon.svg
  public/svgs/noticeIcon.svg
  public/svgs/reviewListIcon.svg
  public/svgs/userEditIcon.svg
  src/Router.tsx
  src/assets/images/pngs/default_dog_image_1.png
  src/assets/images/pngs/default_dog_image_2.png
  src/assets/images/pngs/kakao_icon_image.png
  src/assets/images/svgs/HeartIcon.tsx
  src/assets/images/svgs/LogoutIcon.tsx
  src/assets/images/svgs/NoticeIcon.tsx
  src/assets/images/svgs/ReviewListIcon.tsx
  src/assets/images/svgs/UserEditIcon.tsx
  src/assets/images/svgs/index.ts
  src/common/components/layout/index.tsx
  src/common/constants/route.ts
  src/common/types/index.ts
  src/mocks/data/dogData.ts
  src/mocks/data/userData.ts
  src/pages/my/components/profile/index.tsx
  src/pages/my/constants/DogSizeMapping.ts
  src/pages/my/index.styles.ts
  src/pages/my/index.tsx
  src/pages/my/styles/profile.styles.ts
  src/pages/my/utils/calculateAge.ts
  src/pages/myFavorite/index.tsx
  src/service/apis/user/index.types.ts
  src/styles/GlobalStyles.ts
Labels: ✨ feat

#31 feat/SV-153: 즐겨찾기 전체조회 리스트 UI 구현
  public/svgs/starIcon.svg
  src/Router.tsx
  src/assets/images/svgs/StarIcon.tsx
  src/pages/my/index.tsx
  src/pages/myFavorite/constants/placeCategoryMapping.ts
  src/pages/myFavorite/index.styles.ts
  src/pages/myFavorite/index.tsx
  src/pages/myFavorite/types/placeCategoryMappingType.ts
Labels: ✨ feat

#29 feat/SV-155: 내가 쓴 리뷰 페이지 UI 구현
  public/svgs/TrashcanIcon.svg
  src/Router.tsx
  src/assets/images/svgs/TrashcanIcon.tsx
  src/assets/images/svgs/index.ts
  src/common/components/layout/index.tsx
  src/common/constants/route.ts
  src/common/utils/findKeywordById.ts
  src/common/utils/findLabelNameById.ts
  src/mocks/data/userReview.ts
  src/pages/detail/index.tsx
  src/pages/myReview/components/LabelCard.tsx
  src/pages/myReview/components/ReviewCard.tsx
  src/pages/myReview/index.tsx
  src/pages/myReview/styles/LabelCard.style.ts
  src/pages/myReview/styles/ReviewCard.style.ts
  src/pages/myReview/styles/index.style.ts
  src/service/apis/user/index.types.ts
Labels: ✨ feat

#32 fix/SV-162: 마이페이지 스크롤 구현
  src/assets/images/svgs/index.ts
  src/pages/my/index.styles.ts
Labels: ✨ feat

#30 feat/SV-18: 회원가입 UI 구현
  .gitignore
  public/svgs/LoginBackgroundimg.svg
  public/svgs/NoStrokeStar.svg
  src/Router.tsx
  src/assets/images/svgs/NoStrokeStar.tsx
  src/assets/images/svgs/index.ts
  src/common/components/layout/index.tsx
  src/common/constants/dogBreeds.ts
  src/common/constants/route.ts
  src/pages/dogs/index.tsx
  src/pages/dogs/styles/dogs.styles.ts
  src/pages/login/index.tsx
  src/pages/my/components/profile/index.tsx
  src/pages/my/index.tsx
  src/pages/my/styles/profile.styles.ts
  src/pages/signUp/index.tsx
  src/pages/signUp/styles/signUp.styles.ts
  src/styles/GlobalStyles.ts
Labels: ✨ feat

#36 feat/SV-231: axios 인스턴스 생성 및 인터셉터 추가
  src/service/apis/index.ts
Labels: ✨ feat

#37 fix/SV-121: 마커 클릭 시 카테고리 아이콘 반영하도록 수정, 기본 폰트 색상 설정
  public/svgs/AccommodationClickMarker.svg
  public/svgs/CafeClickMarker.svg
  public/svgs/GalleryClickMarker.svg
  public/svgs/MuseumClickMarker.svg
  public/svgs/ParkClickMarker.svg
  public/svgs/PlaygroundClickMarker.svg
  public/svgs/RestaurantClickMarker.svg
  public/svgs/RestaurantTag.svg
  public/svgs/TravelClickMarker.svg
  public/svgs/TravelTag.svg
  public/svgs/accommodationMarker.svg
  public/svgs/accommodationTag.svg
  public/svgs/amusementparkMarker.svg
  public/svgs/artgalleryTag.svg
  public/svgs/cafeTag.svg
  public/svgs/clickMarker.svg
  public/svgs/galleryMarker.svg
  public/svgs/galleryTag.svg
  public/svgs/hotelMarker.svg
  public/svgs/museumMarker.svg
  public/svgs/museumTag.svg
  public/svgs/parkMarker.svg
  public/svgs/parkTag.svg
  public/svgs/playgroundMarker.svg
  public/svgs/playgroundTag.svg
  public/svgs/travelMarker.svg
  src/assets/images/svgs/AccommodationClickMarker.tsx
  src/assets/images/svgs/AccommodationMarker.tsx
  src/assets/images/svgs/AccommodationTag.tsx
  src/assets/images/svgs/AmusementparkMarker.tsx
  src/assets/images/svgs/ArtgalleryTag.tsx
  src/assets/images/svgs/CafeClickMarker.tsx
  src/assets/images/svgs/CafeTag.tsx
  src/assets/images/svgs/ClickMarker.tsx
  src/assets/images/svgs/GalleryClickMarker.tsx
  src/assets/images/svgs/GalleryMarker.tsx
  src/assets/images/svgs/GalleryTag.tsx
  src/assets/images/svgs/HotelMarker.tsx
  src/assets/images/svgs/MuseumClickMarker.tsx
  src/assets/images/svgs/MuseumMarker.tsx
  src/assets/images/svgs/MuseumTag.tsx
  src/assets/images/svgs/ParkClickMarker.tsx
  src/assets/images/svgs/ParkMarker.tsx
  src/assets/images/svgs/ParkTag.tsx
  src/assets/images/svgs/PlaygroundClickMarker.tsx
  src/assets/images/svgs/PlaygroundMarker.tsx
  src/assets/images/svgs/PlaygroundTag.tsx
  src/assets/images/svgs/RestaurantClickMarker.tsx
  src/assets/images/svgs/RestaurantMarker.tsx
  src/assets/images/svgs/RestaurantTag.tsx
  src/assets/images/svgs/TravelClickMarker.tsx
  src/assets/images/svgs/TravelMarker.tsx
  src/assets/images/svgs/TravelTag.tsx
  src/assets/images/svgs/index.ts
  src/pages/main/components/categoryBar/index.tsx
  src/pages/main/components/customMarker/index.tsx
  src/pages/main/constants/categoryBar.ts
  src/pages/main/index.tsx
  src/pages/main/types/index.ts
  src/styles/GlobalStyles.ts
Labels: 👽 chore, 🔧fix

#40 feat/SV-66: 지도 장소 조회 API 부착
  src/common/constants/categories.ts
  src/common/constants/reviewLabels.ts
  src/mocks/data/markerData.ts
  src/pages/main/constants/categoryBar.ts
  src/pages/main/hooks/useMapCenter.ts
  src/pages/main/index.tsx
  src/pages/main/types/index.ts
  src/pages/main/utils/coordinateUtils.ts
  src/pages/main/utils/markerUtils.tsx
  src/pages/my/index.tsx
  src/pages/myFavorite/constants/placeCategoryMapping.ts
  src/service/apis/place/index.ts
  src/service/apis/place/index.type.ts
Labels: ✨ feat

#44 fix/SV-132: S3 이미지 업로드 및 삭제 기능 개선, 미디어 타입 수정
  src/common/utils/uploadImageToS3.tsx
  src/mocks/data/todaymungDetailData.ts
  src/pages/main/index.tsx
  src/pages/my/index.tsx
  src/pages/recommend/index.tsx
  src/pages/search/index.tsx
  src/pages/todaymung/index.tsx
  src/pages/todaymung/styles/TodayMungCalendarRoot.style.ts
  src/pages/todaymungDetail/components/imageCard/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungDetail/types/DiaryType.ts
  src/pages/todaymungPlaceRegist/components/SearchResultCard.tsx
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungPlaceRegist/styles/SearchResultCard.style.ts
  src/pages/todaymungWrite/components/MediaGroup.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
  src/pages/todaymungWrite/styles/VisitedPlaceCard.style.ts
  src/service/apis/diary/index.type.ts
  src/service/apis/place/index.ts
  src/service/apis/review/index.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#45 feat/SV-173: 장소 카테고리 필터링 API 부착
  src/common/components/header/index.styles.ts
  src/common/constants/ui.ts
  src/mocks/data/placeMap.ts
  src/mocks/data/postDetail.ts
  src/mocks/mockApis/place.ts
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/components/categoryBar/index.tsx
  src/pages/main/constants/categoryBar.ts
  src/pages/main/index.tsx
  src/pages/main/styles/Content.style.ts
  src/pages/main/utils/markerUtils.tsx
  src/pages/myFavorite/index.tsx
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/todaymungPlaceRegist/components/SearchResultCard.tsx
  src/pages/todaymungPlaceRegist/index.tsx
  src/service/apis/place/index.ts
  src/service/apis/place/index.type.ts
Labels: ✨ feat

#43 Feat/SV-85: 상세페이지 API 부착완료
  src/pages/todaymung/components/convert/index.tsx
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/components/todayMungListCard/index.tsx
  src/pages/todaymung/queries/index.ts
  src/pages/todaymung/styles/Convert.style.ts
  src/pages/todaymung/styles/TodayMungList.style.ts
  src/pages/todaymung/styles/TodayMungListCard.style.ts
  src/pages/todaymungDetail/components/dogTag/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungDetail/queries/index.ts
  src/pages/todaymungDetail/styles/TextContent.style.ts
  src/pages/todaymungDetail/styles/index.style.ts
  src/pages/todaymungDetail/types/DiaryType.ts
  src/service/apis/diaryDetail/index.ts
Labels: ✨ feat

#47 feat/SV-94: 오늘멍 장소 검색 API 부착 및 검색 결과 없을 경우 예외처리
  public/svgs/LiedownDog.svg
  src/assets/images/svgs/LiedownDog.tsx
  src/assets/images/svgs/PlusIcon.tsx
  src/assets/images/svgs/index.ts
  src/common/components/button/Button.style.ts
  src/common/components/button/Button.tsx
  src/common/components/button/Button.type.ts
  src/common/components/modal/index.styles.ts
  src/pages/search/components/SearchHistoryList.tsx
  src/pages/search/index.tsx
  src/pages/todaymungPlaceRegist/components/ReviewCard.tsx
  src/pages/todaymungPlaceRegist/components/SearchList.tsx
  src/pages/todaymungPlaceRegist/components/SearchResultCard.tsx
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungPlaceRegist/queries/index.ts
  src/pages/todaymungPlaceRegist/styles/SearchList.style.ts
  src/pages/todaymungPlaceRegist/styles/index.style.ts
  src/pages/todaymungWrite/components/VisitedPlaceCard.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/styles/VisitedPlaceCard.style.ts
  src/service/apis/place/index.ts
  src/service/apis/place/index.type.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#48 feat/SV-174: 바텀시트 카테고리 한글로 변경
  src/pages/main/components/bottomSheet/Content.tsx
Labels: ✨ feat

#50 feat/SV-151: 내 리뷰 모아보기 조회, 삭제 API 구현
  src/pages/myReview/components/ReviewCard.tsx
  src/pages/myReview/index.tsx
  src/pages/myReview/queries/index.ts
  src/pages/todaymungWrite/styles/VisitedPlaceCard.style.ts
  src/service/apis/review/index.ts
  src/service/apis/review/index.type.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#52 feat/SV-238: 메인페이지에서 장소검색 API 연동 및 검색 페이지 UI 예외처리
  src/common/components/layout/index.tsx
  src/pages/main/constants/categoryBar.ts
  src/pages/main/index.tsx
  src/pages/myReview/index.tsx
  src/pages/search/components/NoSearchHistory.tsx
  src/pages/search/components/NoSearchResponse.tsx
  src/pages/search/index.tsx
  src/pages/search/styles/NoSearchHistory.style.ts
  src/pages/todaymungDetail/index.tsx
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#54 hotfix/SV-256: 리뷰등록, 오늘멍 등록 실패시에도 리뷰, 오늘멍 기록 전체 삭제
  src/pages/todaymungWrite/queries/index.ts
Labels: ☠️ hotfix

#55 hotfix/SV-256: 오늘멍 등록 실패시 오늘멍 내역 모두 삭제되도록 수정
  src/pages/todaymungWrite/queries/index.ts
Labels: ☠️ hotfix

#56 feat/SV-250: 도로명 주소를 위도경도로 바꿔주는 함수 구현
  src/pages/signUp/index.tsx
  src/pages/signUp/utils/convertAddressToLatlng.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#57 feat/SV-99: 추천페이지 API 연결
  src/Router.tsx
  src/mocks/data/recommend.ts
  src/pages/recommend/components/IndexGuest.tsx
  src/pages/recommend/components/IndexUser.tsx
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/recommend/index.tsx
  src/pages/recommend/queries/index.ts
  src/pages/recommend/styles/RecommendCard.style.ts
  src/pages/recommend/styles/index.style.ts
  src/service/apis/place/index.type.ts
  src/service/apis/recommend/index.ts
Labels: ✨ feat

#60 feat/SV-213: 뒤로가기 로직 구현
  src/common/components/header/index.tsx
  src/common/components/header/index.type.ts
  src/common/components/layout/index.tsx
Labels: ✨ feat

#61 feat/SV-53: 바텀시트 필터 기능 구현
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/bottomSheet/Filter.tsx
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/types/filter.ts
  src/pages/main/types/index.ts
  src/service/apis/place/index.type.ts
Labels: ✨ feat

#67 feat/SV-259: 빈 화면 UI 예외처리, 로딩중 로티 컴포넌트 생성, 로그인 유도 모달 구현
  package.json
  public/assets/lottie/LoadingLottie.json
  public/assets/lottie/SkeletonLottie.json
  public/assets/lottie/nolmungLottie.json
  public/svgs/StandBrownDog.svg
  src/assets/images/svgs/StandBrownDog.tsx
  src/assets/images/svgs/index.ts
  src/assets/lottie/LoadingLottie.json
  src/assets/lottie/SkeletonLottie.json
  src/assets/lottie/nolmungLottie.json
  src/common/components/loginPromptModal/index.style.ts
  src/common/components/loginPromptModal/index.tsx
  src/common/components/lottie/index.style.ts
  src/common/components/lottie/index.tsx
  src/common/components/modal/index.styles.ts
  src/common/components/modal/index.tsx
  src/common/components/modal/index.type.ts
  src/common/components/noResultUI/index.style.ts
  src/common/components/noResultUI/index.tsx
  src/pages/detail/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/index.tsx
  src/pages/myFavorite/index.tsx
  src/pages/myReview/index.tsx
  src/pages/recommend/components/IndexUser.tsx
  src/stores/useLoginPromptModalStore.ts
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ✨ feat

#71 feat/SV-215: PrivateRoute 처리
  src/App.tsx
  src/Router.tsx
  src/common/components/layout/index.tsx
  src/common/components/loginPromptModal/index.style.ts
  src/common/components/loginPromptModal/index.tsx
  src/common/components/modal/index.styles.ts
  src/common/components/modal/index.tsx
  src/common/components/tabBar/index.styles.ts
  src/common/components/tabBar/index.tsx
  src/common/utils/getIsLogin.ts
  src/common/utils/useIsReviewEmpty.ts
  src/common/utils/useIsTodaymungEmpty.ts
  src/pages/detail/index.tsx
  src/pages/main/index.tsx
  src/pages/todaymungDetail/components/editButton/index.tsx
  src/route/PrivateRoute.tsx
  src/route/Router.tsx
  src/service/apis/index.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#69 Feat/SV-39: 반려견 등록 수정 삭제
  src/Router.tsx
  src/common/components/layout/index.tsx
  src/common/constants/route.ts
  src/pages/dogEdit/index.tsx
  src/pages/dogEdit/styles/dogsEdit.styles.ts
  src/pages/dogs/index.tsx
  src/pages/my/components/myDogs/index.tsx
  src/pages/my/components/profile/index.tsx
  src/pages/my/index.styles.ts
  src/pages/my/index.tsx
  src/pages/my/styles/myDogs.styles.ts
  src/pages/signUp/DatePicker.tsx
Labels: ✨ feat

#74 feat/SV-215: 404 페이지 처리
  src/pages/404/index.style.ts
  src/pages/404/index.tsx
  src/pages/detail/index.tsx
  src/pages/detail/styles/detail.styles.ts
  src/pages/myFavorite/hooks/index.ts
  src/route/Router.tsx
  src/service/apis/place/index.type.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#75 feat/SV-272: 사용자 현재 위치 마커 UI 구현
  public/svgs/CurrentLocationMarker.svg
  src/assets/images/svgs/CurrentLocationMarker.tsx
  src/assets/images/svgs/index.ts
  src/pages/main/index.tsx
  src/pages/main/stores/useLocationStore.ts
Labels: ✨ feat

#76 feat/SV-18: 마이페이지 유저 정보 조회, 수정 기능 구현
  package.json
  public/addressPopup.html
  src/Router.tsx
  src/common/constants/route.ts
  src/global.d.ts
  src/pages/dogEdit/index.tsx
  src/pages/dogs/index.tsx
  src/pages/login/components/KakaoCallbackHandler.tsx
  src/pages/login/index.tsx
  src/pages/my/index.styles.ts
  src/pages/my/index.tsx
  src/pages/signUp/components/DatePicker.tsx
  src/pages/signUp/components/DaumPost.tsx
  src/pages/signUp/index.tsx
  src/pages/signUp/styles/signUp.styles.ts
  src/pages/userEdit/index.tsx
  src/route/Router.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.json
  yarn.lock
Labels: ✨ feat

#77 feat/SV-273: 찜한 장소, 방문한 장소 카테고리 클릭 시 예외처리
  src/pages/main/index.tsx
Labels: ✨ feat

#79 feat/SV-215: 모든 alert 메시지 toast 메시지로 변경, window.confirm은 modal로 변경
  src/common/components/layout/index.tsx
  src/common/components/tabBar/index.tsx
  src/common/utils/uploadImageToS3.tsx
  src/pages/dogEdit/queries/index.ts
  src/pages/dogs/queries/index.ts
  src/pages/login/components/KakaoCallbackHandler.tsx
  src/pages/myReview/queries/index.ts
  src/pages/signUp/index.tsx
  src/pages/todaymungDetail/queries/index.ts
  src/pages/todaymungEdit/components/Editor.tsx
  src/pages/todaymungEdit/components/MediaGroup.tsx
  src/pages/todaymungEdit/index.tsx
  src/pages/todaymungEdit/queries/index.ts
  src/pages/todaymungWrite/components/Editor.tsx
  src/pages/todaymungWrite/components/MediaGroup.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
  src/pages/todaymungWrite/styles/index.style.ts
  src/pages/userEdit/index.tsx
  src/stores/useConfirmModalStore.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#80 feat/SV-215: 로딩중 적용 안된 페이지 로딩 컴포넌트로 수정
  src/pages/todaymung/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungPlaceRegist/index.tsx
Labels: ✨ feat

#81 feat/SV-18: 유저 도로명 주소 등록 DaumPost(위도,경도 적용) 구현, 생년월일 DatePicker 스타일 커스텀, 마이페이지 스타일 상세 수정 추가
  src/pages/signUp/components/DatePicker.tsx
  src/pages/signUp/components/DaumPost.tsx
  src/pages/signUp/index.tsx
  src/pages/userEdit/index.tsx
Labels: ✨ feat

#83 fix/SV-215: 추천페이지 이벤트 캡쳐링 방지
  src/common/components/layout/index.tsx
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/index.tsx
  src/pages/recommend/components/IndexGuest.tsx
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/todaymungPlaceRegist/queries/index.ts
Labels: ✨ feat

#82 fix/SV-274: 마커 폰트 사이즈 동적으로 변경하게 수정
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/customMarker/index.tsx
  src/pages/main/index.tsx
  src/pages/main/styles/CustomMarkerComponent.styles.ts
  src/route/Router.tsx
  src/service/apis/index.ts
Labels: 🔧fix

#84 feat/SV-215: axios request interceptor 적용
  src/pages/main/styles/CategoryBar.style.ts
  src/pages/recommend/components/IndexGuest.tsx
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/todaymungPlaceRegist/styles/index.style.ts
  src/service/apis/index.ts
Labels: ✨ feat

#85 feat/SV-270: 오늘멍 예외처리 및 mui 의존성 버전 충돌 해결
  .yarn/install-state.gz
  package.json
  src/pages/main/index.tsx
  src/pages/todaymung/components/convert/index.tsx
  src/pages/todaymung/components/noDiaryList/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/index.tsx
  src/pages/todaymung/styles/Convert.style.ts
  src/pages/todaymung/styles/TodayMungCalendarRoot.style.ts
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungWrite/index.tsx
  src/route/Router.tsx
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ✨ feat, 🔧fix

#86 feat/SV-215: 로그아웃 및 설문 탭 구현
  src/common/components/layout/index.tsx
  src/pages/my/index.tsx
  src/pages/todaymungWrite/index.tsx
Labels: ✨ feat

#87 fix/SV-215: 로그인 화면 스크롤 가능하도록 수정
  src/pages/login/index.tsx
  src/pages/login/styles/login.styles.ts
Labels: ✨ feat

#90 fix/SV-284: 모바일 환경에서 시설 상세 페이지 padding-bottom 추가
  src/pages/detail/index.tsx
  src/pages/detail/styles/detail.styles.ts
  src/pages/myReview/queries/index.ts
Labels: ✨ feat

#91 feat/SV-311 : 반려견 기본 프로필 사진 수정
  .yarn/install-state.gz
  package.json
  src/common/constants/uploadPath.ts
  src/common/utils/uploadImageToS3.tsx
  src/pages/dogEdit/index.tsx
  src/pages/dogs/index.tsx
  src/pages/my/components/profile/index.tsx
  src/pages/my/styles/profile.styles.ts
  src/pages/todaymungEdit/components/MediaGroup.tsx
  src/pages/todaymungWrite/components/MediaGroup.tsx
  yarn.lock
Labels: ✨ feat

#92 feat/SV-312: 마이페이지에서 반려견 등록 2번 클릭 한번 클릭으로 수정
  src/pages/my/components/myDogs/index.tsx
  src/pages/my/components/profile/index.tsx
  src/pages/my/index.tsx
  src/pages/todaymungDetail/index.tsx
Labels: ✨ feat

#93 feat/SV-313: 반려견length가 0이하면 조건부 렌더링
  src/pages/todaymungDetail/index.tsx
Labels: 🔧fix

#94 fix/SV-287: 오늘멍 장소등록 페이지 UX 개선 및 라우팅 수정
  src/common/components/button/Button.style.ts
  src/common/components/layout/index.tsx
  src/pages/main/index.tsx
  src/pages/search/styles/index.style.ts
  src/pages/todaymungPlaceRegist/styles/ReviewCard.style.ts
  src/pages/todaymungPlaceRegist/styles/index.style.ts
  src/service/apis/index.ts
Labels: ✨ feat

#96 feat/SV-291: 로그인 화면 높이 수정
  src/pages/login/index.tsx
  src/pages/login/styles/login.styles.ts
Labels: ✨ feat, 🔧fix

#95 fix/SV-295: textarea 클릭시 줌 안 되게 수정 및 오늘멍 작성하기 페이지 Padding 추가
  index.html
  src/pages/todaymungEdit/styles/Editor.style.ts
  src/pages/todaymungPlaceRegist/styles/index.style.ts
  src/pages/todaymungWrite/components/Editor.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/styles/Editor.style.ts
  src/pages/todaymungWrite/styles/index.style.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#98 feat/SV-299: 검색창 onClick 이벤트 핸들러에 함수 전달 방식 변경
  src/pages/todaymungPlaceRegist/index.tsx
Labels: ✨ feat

#100 feat/SV-290: 오늘멍 리뷰 등록 및 오늘멍 등록 로직 분리
  src/pages/todaymungDetail/queries/index.ts
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungPlaceRegist/styles/index.style.ts
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
Labels: ✨ feat

#101 feat/SV-18: 회원정보 입력 창 높이 조절
  src/pages/signUp/components/DatePicker.tsx
  src/pages/signUp/components/DaumPost.tsx
  src/pages/signUp/styles/signUp.styles.ts
  yarn.lock
Labels: ✨ feat

#102 feat/SV-318: 다른 분들이 작성한 오늘멍 수정삭제 막기
  src/common/utils/configToken.ts
  src/pages/detail/components/TodayMungCard.tsx
  src/pages/dogs/index.tsx
  src/pages/todaymung/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungDetail/types/DiaryType.ts
  src/pages/todaymungWrite/queries/index.ts
Labels: ✨ feat

#105 feat/SV-18: 회원가입 GenderSelect 버튼 크기 input 크기 조절
  src/pages/signUp/components/DaumPost.tsx
  src/pages/signUp/styles/signUp.styles.ts
Labels: 👽 chore

#106 fix/SV-293: 강아지 카드 컴포넌트 스타일 수정 (flex:1 제거)
  src/pages/my/styles/profile.styles.ts
Labels: 🔧fix

#108 fix/SV-324: bottomCard 뒤로가기 클릭 시 높이 문제 해결
  src/common/hooks/useCustomBack.ts
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/index.tsx
  tsconfig.app.tsbuildinfo
Labels: ☠️ hotfix, 🔧fix

#111 fix/SV-327: 리뷰 조회 캐싱 시간 삭제
  src/pages/myReview/queries/index.ts
Labels: ☠️ hotfix, 🔧fix

#113 feat/SV-325 : 강아지 5명 이상이면 alert 띄우기
  .yarn/install-state.gz
  src/pages/dogEdit/index.tsx
  src/pages/dogEdit/styles/dogsEdit.styles.ts
  src/pages/dogs/index.tsx
  src/pages/dogs/styles/dogs.styles.ts
  src/pages/my/components/myDogs/index.tsx
  src/pages/my/index.tsx
  src/pages/my/styles/myDogs.styles.ts
  src/pages/signUp/styles/signUp.styles.ts
  src/pages/todaymung/index.tsx
  src/pages/todaymungDetail/index.tsx
  yarn.lock
Labels: ✨ feat

#114 fix/SV-328: 리뷰 로직 수정
  src/common/components/layout/index.tsx
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungPlaceRegist/queries/index.ts
  src/pages/todaymungPlaceRegist/stores/reviewStore.ts
  src/pages/todaymungPlaceRegist/styles/index.style.ts
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
  src/pages/todaymungWrite/stores/todayMungStore.ts
  src/service/apis/diary/index.ts
  src/service/apis/review/index.ts
  src/service/apis/review/index.type.ts
  src/stores/useReviewConfirmModalStore.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#115 hotfix/SV-328: 장소 등록 페이지 정상 뒤로가기 예외처리
  src/common/components/layout/index.tsx
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#117 chore/SV-328: 임시 로컬스토리지 초기화 버튼 구현
  src/pages/recommend/components/IndexGuest.tsx
Labels: ✨ feat

#118 fix/SV-328: 임시 로컬스토리지 초기화 버튼 구현 및 추천페이지, 마이페이지 높이 수정
  src/common/components/lottie/index.style.ts
  src/pages/detail/styles/detail.styles.ts
  src/pages/dogEdit/styles/dogsEdit.styles.ts
  src/pages/dogs/styles/dogs.styles.ts
  src/pages/my/index.styles.ts
  src/pages/my/styles/myDogs.styles.ts
  src/pages/my/styles/profile.styles.ts
  src/pages/myReview/styles/index.style.ts
  src/pages/recommend/components/IndexUser.tsx
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/recommend/styles/index.style.ts
  src/pages/todaymung/styles/UserInfo.style.ts
  src/pages/todaymung/styles/index.style.ts
  src/pages/todaymungDetail/components/editButton/index.tsx
  src/pages/todaymungEdit/styles/MediaGroup.style.ts
  src/pages/todaymungWrite/styles/MediaGroup.style.ts
  tsconfig.app.tsbuildinfo
Labels: ☠️ hotfix, 🔧fix

#119 fix/SV-330: QA 버그 픽스
  src/common/components/layout/index.tsx
  src/pages/detail/index.tsx
  src/pages/detail/querys/index.ts
  src/pages/detail/styles/detail.styles.ts
  src/pages/dogEdit/index.tsx
  src/pages/login/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/todaymungDetail/components/editButton/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungDetail/queries/index.ts
  src/pages/todaymungEdit/index.tsx
  src/pages/todaymungEdit/queries/index.ts
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
  tsconfig.app.tsbuildinfo
Labels: ☠️ hotfix, 🔧fix

#122 feat/SV-214: sentry 부착
  .gitignore
  package.json
  src/main.tsx
  src/pages/recommend/components/IndexGuest.tsx
  src/pages/recommend/components/IndexUser.tsx
  src/route/Router.tsx
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ✨ feat

#123 feat/SV-325: 엑박 및 여러 에러 수정
  src/common/components/layout/index.tsx
  src/pages/dogEdit/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
  src/pages/todaymung/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungWrite/components/DogCard.tsx
Labels: ☠️ hotfix

#124 fix/SV-214: 마이페이지 로딩 스피너 로티 부착
  src/pages/my/index.tsx
Labels: ✨ feat

#127 feat/SV-214: OpenGraph 메타 태그 설정
  index.html
  src/main.tsx
Labels: ✨ feat

#128 feat/SV-331: 기존 mediaUrl로 받던것 mediaList로 수정 및 비디오 기본 default Img 추가
  .yarn/install-state.gz
  src/mocks/data/todaymungData.ts
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/components/todayMungListCard/index.tsx
  src/pages/todaymung/index.tsx
  src/pages/todaymung/types/TodayMungList.type.ts
  yarn.lock
Labels: ✨ feat

#131 fix/SV-333: 즐겨찾기 목록 오류 수정, 지도 줌 수정, 토스트 메세지 UI 수정
  src/App.tsx
  src/pages/main/index.tsx
  src/pages/myFavorite/hooks/index.ts
  src/pages/myFavorite/index.tsx
Labels: 👽 chore, 🔧fix

#132 feat/SV-214: GA 배포용으로 수정
  index.html
  src/pages/login/components/KakaoCallbackHandler.tsx
  src/pages/login/components/KakaoLoginButton.tsx
Labels: ✨ feat

#133 release 1.0.2: 지도 minZoom 변경, toast 메시지 ui 수정, 즐겨찾기 버그 수정, 오늘멍 미디어 프리뷰 수정, 카카오 로그인 운영서버로 변경
  index.html
  src/App.tsx
  src/pages/login/components/KakaoCallbackHandler.tsx
  src/pages/login/components/KakaoLoginButton.tsx
  src/pages/main/index.tsx
  src/pages/myFavorite/hooks/index.ts
  src/pages/myFavorite/index.tsx
  src/pages/todaymungWrite/components/MediaGroup.tsx
Labels: ☠️ hotfix

#134 hotfix/SV-368: 시설 상세 페이지 undefined 관련 버그 수정
  src/pages/detail/index.tsx
Labels: ☠️ hotfix

#135 release 1.0.3: 시설 상세페이지 버그 수정
  src/pages/detail/index.tsx
Labels: ❤️‍🔥 release

#136 fix/SV-331: 오늘멍 작성 안되던 버그 수정 (아마 버튼 문제 예상 버튼 로직수정)
  src/pages/todaymung/components/noDiaryList/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
Labels: 🔧fix

#137 release 1.0.4 : 오늘멍 기존에 작성되어있다고 나오는 버그 수정
  src/pages/todaymung/components/noDiaryList/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
Labels: ☠️ hotfix, ❤️‍🔥 release

#138 hotfix/SV-368: 카카오 로그인 url env 값으로 변환, 메인페이지 GA 커스텀 이벤트 부착
  package.json
  src/App.tsx
  src/pages/login/components/KakaoLoginButton.tsx
  src/pages/main/index.tsx
  src/pages/main/styles/index.style.ts
  src/service/googleAnalytics/analytics.ts
  src/service/googleAnalytics/events.ts
  src/service/googleAnalytics/usePageTracking.ts
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ☠️ hotfix

#140 fix/SV-368: 메인페이지 지도 height 조절
  src/pages/main/styles/index.style.ts
Labels: 🔧fix

#139 release 1.0.5: 카카오 로그인 url env 값으로 변환, 메인페이지 GA 커스텀 이벤트 부착
  package.json
  src/App.tsx
  src/pages/login/components/KakaoLoginButton.tsx
  src/pages/main/index.tsx
  src/pages/main/styles/index.style.ts
  src/service/googleAnalytics/analytics.ts
  src/service/googleAnalytics/events.ts
  src/service/googleAnalytics/usePageTracking.ts
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ☠️ hotfix

#141 feat/SV-368: 페이지별 커스텀 GA 이벤트 부착
  src/common/components/loginPromptModal/index.tsx
  src/pages/detail/index.tsx
  src/pages/dogEdit/index.tsx
  src/pages/dogs/index.tsx
  src/pages/login/components/KakaoLoginButton.tsx
  src/pages/login/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/categoryBar/index.tsx
  src/pages/main/index.tsx
  src/pages/my/index.tsx
  src/pages/myFavorite/index.tsx
  src/pages/myReview/index.tsx
  src/pages/recommend/components/IndexGuest.tsx
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/search/index.tsx
  src/pages/signUp/index.tsx
  src/pages/todaymung/components/convert/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/components/todayMungListCard/index.tsx
  src/pages/todaymungDetail/components/editButton/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungEdit/components/MediaGroup.tsx
  src/pages/todaymungEdit/index.tsx
  src/pages/todaymungPlaceRegist/components/ReviewCard.tsx
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungWrite/components/DogCard.tsx
  src/pages/todaymungWrite/components/MediaGroup.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/userEdit/index.tsx
  src/service/googleAnalytics/events.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#142 release 1.0.6: GA 커스텀 이벤트 부착
  src/common/components/loginPromptModal/index.tsx
  src/pages/detail/index.tsx
  src/pages/dogEdit/index.tsx
  src/pages/dogs/index.tsx
  src/pages/login/components/KakaoLoginButton.tsx
  src/pages/login/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/categoryBar/index.tsx
  src/pages/main/index.tsx
  src/pages/my/index.tsx
  src/pages/myFavorite/index.tsx
  src/pages/myReview/index.tsx
  src/pages/recommend/components/IndexGuest.tsx
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/search/index.tsx
  src/pages/signUp/index.tsx
  src/pages/todaymung/components/convert/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/components/todayMungListCard/index.tsx
  src/pages/todaymungDetail/components/editButton/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungEdit/components/MediaGroup.tsx
  src/pages/todaymungEdit/index.tsx
  src/pages/todaymungPlaceRegist/components/ReviewCard.tsx
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungWrite/components/DogCard.tsx
  src/pages/todaymungWrite/components/MediaGroup.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/userEdit/index.tsx
  src/service/googleAnalytics/events.ts
  tsconfig.app.tsbuildinfo
Labels: ❤️‍🔥 release

#143 hotfix/SV-368: 시설 상세 페이지 렌더링 버그 수정
  src/pages/detail/index.tsx
Labels: ☠️ hotfix

#144 hotfix/SV-368: 시설 상세 페이지 훅 렌더링 버그 수정
  src/pages/detail/index.tsx
Labels: ☠️ hotfix, 🔧fix

#145 hotfix/SV-368: 훅 렌더링 버그 수정
  src/pages/detail/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungEdit/queries/index.ts
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungPlaceRegist/queries/index.ts
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
Labels: ☠️ hotfix

#146 release 1.0.8: 훅 렌더링 버그 수정
  src/pages/detail/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungEdit/queries/index.ts
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungPlaceRegist/queries/index.ts
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
Labels: ☠️ hotfix

#148 feat/SV-364: 로그인 후 2.5초간 놀멍 로티 적용
  src/pages/login/components/KakaoCallbackHandler.tsx
Labels: ✨ feat

#149 hotfix/SV-368: 뒤로가기 버그 수정 및 sentry url 재설정
  src/common/components/layout/index.tsx
  src/common/components/loginPromptModal/index.style.ts
  src/main.tsx
  src/pages/main/queries/index.ts
  src/pages/signUp/components/DaumPost.tsx
  src/pages/signUp/index.tsx
  src/pages/userEdit/index.tsx
Labels: ☠️ hotfix, 🔧fix

#151 feat/SV-368: 뒤로가기 버튼 이벤트 부착
  src/common/components/layout/index.tsx
  src/pages/detail/index.tsx
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#150 feat/SV-372: 시차로 인하여 오늘멍이 오늘 작성안되는 버그 수정
  .yarn/install-state.gz
  src/common/components/button/Button.tsx
  src/common/components/button/Button.type.ts
  src/common/components/header/index.tsx
  src/common/components/layout/flex.ts
  src/common/components/layout/index.tsx
  src/common/utils/convertFormatDate.ts
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/components/todayMungListCard/index.tsx
  src/pages/todaymungDetail/index.tsx
  yarn.lock
Labels: ✨ feat

#153 release 1.0.8: 로티 등록, 버그 수정, 뒤로가기 GA 이벤트 부착
  .yarn/install-state.gz
  README.md
  src/common/components/button/Button.tsx
  src/common/components/button/Button.type.ts
  src/common/components/header/index.styles.ts
  src/common/components/header/index.tsx
  src/common/components/layout/flex.ts
  src/common/components/layout/index.tsx
  src/common/components/loginPromptModal/index.style.ts
  src/common/components/loginPromptModal/index.tsx
  src/common/components/lottie/index.style.ts
  src/common/components/tabBar/index.styles.ts
  src/common/constants/ui.ts
  src/common/utils/convertFormatDate.ts
  src/main.tsx
  src/pages/detail/index.tsx
  src/pages/login/components/KakaoCallbackHandler.tsx
  src/pages/main/index.tsx
  src/pages/main/queries/index.ts
  src/pages/main/styles/Content.style.ts
  src/pages/main/styles/index.style.ts
  src/pages/my/index.styles.ts
  src/pages/recommend/components/RecommendCard.tsx
  src/pages/recommend/styles/RecommendCard.style.ts
  src/pages/signUp/components/DaumPost.tsx
  src/pages/signUp/index.tsx
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/components/todayMungListCard/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungPlaceRegist/components/ReviewCard.tsx
  src/pages/todaymungPlaceRegist/styles/ReviewCard.style.ts
  src/pages/todaymungWrite/components/VisitedPlaceCard.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/styles/DogCard.style.ts
  src/pages/todaymungWrite/styles/Editor.style.ts
  src/pages/todaymungWrite/styles/VisitedPlaceCard.style.ts
  src/pages/todaymungWrite/styles/index.style.ts
  src/pages/userEdit/index.tsx
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ❤️‍🔥 release

#155 release 1.0.9: 오타 수정 및 오늘멍 상세보기 장소 클릭시 장소 상세로 이동 구현, 로그인 유도 모달 버그수정
  README.md
  public/mockServiceWorker.js
  src/common/components/header/index.tsx
  src/common/components/loginPromptModal/index.style.ts
  src/pages/main/components/categoryBar/index.tsx
  src/pages/todaymungDetail/components/placeTag/index.tsx
  src/pages/todaymungDetail/styles/PlaceTagCard.style.ts
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: 🔧fix

#160 feat/SV-368: 바텀시트 필터에 GA 이벤트 부착
  src/pages/main/components/bottomSheet/index.tsx
Labels: ✨ feat

#161 release 1.0.9: 상단바 숨김 처리 및 회원 가입 버그 수정, 오늘멍 버그 수정, bottomSheet filter에 GA 부착
  public/svgs/LargeDog.svg
  public/svgs/SmallDog.svg
  src/assets/images/svgs/LargeDog.tsx
  src/assets/images/svgs/SmallDog.tsx
  src/common/components/layout/index.tsx
  src/pages/dogs/styles/dogs.styles.ts
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/styles/index.style.ts
  src/pages/signUp/styles/signUp.styles.ts
  src/pages/todaymungWrite/components/VisitedPlaceCard.tsx
  src/pages/todaymungWrite/styles/Editor.style.ts
Labels: ❤️‍🔥 release

#162 feat/SV-372: 전체적으로 주석 추가 및 오늘멍 조회부분 css 수정
  .yarn/install-state.gz
  src/common/components/layout/index.tsx
  src/common/components/loginPromptModal/index.tsx
  src/common/components/noResultUI/index.tsx
  src/common/components/searchInput/index.tsx
  src/common/components/tabBar/index.tsx
  src/common/components/tabBar/utils/tabUtils.ts
  src/common/constants/categories.ts
  src/common/constants/dogBreeds.ts
  src/common/constants/reviewLabels.ts
  src/common/constants/tabBarItems.ts
  src/common/constants/uploadPath.ts
  src/common/hooks/useSetDocumentTitle.ts
  src/common/utils/configToken.ts
  src/common/utils/getIsLogin.ts
  src/pages/404/index.tsx
  src/pages/detail/querys/index.ts
  src/pages/dogEdit/index.tsx
  src/pages/dogEdit/queries/index.ts
  src/pages/dogs/queries/index.ts
  src/pages/login/components/KakaoCallbackHandler.tsx
  src/pages/my/utils/calculateAge.ts
  src/pages/signUp/components/DatePicker.tsx
  src/pages/signUp/components/DaumPost.tsx
  src/pages/todaymung/components/noDiaryList/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/styles/Convert.style.ts
  src/pages/todaymung/styles/TodayMungList.style.ts
  src/pages/todaymungDetail/styles/index.style.ts
  src/pages/todaymungEdit/components/DogCard.tsx
  src/pages/todaymungEdit/index.tsx
  src/route/PrivateRoute.tsx
  yarn.lock
Labels: ✨ feat

#163 feat/SV-368: GA에 uuid 설정
  src/App.tsx
  src/common/components/layout/index.tsx
  src/pages/recommend/styles/index.style.ts
Labels: ✨ feat

#164 fix/SV-368: 반려동물 리스트 페이지 뒤로가기 구현 및 즐겨찾기 목록 기능 수정
  src/common/components/layout/index.tsx
  src/pages/myFavorite/hooks/index.ts
  src/pages/myFavorite/index.tsx
  tsconfig.app.tsbuildinfo
Labels: ✨ feat

#167 hotfix/SV-176: 오늘멍 작성하기에서 모달 뜨는 에러 수정
  src/pages/todaymungWrite/index.tsx
Labels: ☠️ hotfix

#168 release 1.1.2: 오늘멍 등록하기에서 미완성된 뱃지 모달 창이 뜨는 오류 수정
  src/pages/todaymungWrite/index.tsx
Labels: ☠️ hotfix, ❤️‍🔥 release

#169 feat/SV-177: 오늘멍 작성하기에서 모달 여는 로직 추가, confetti 이벤트 추가, 커스텀 도메인 리다이렉트 설정
  netlify.toml
  package.json
  public/pngs/event_todaymung.png
  public/pngs/firstBadge.png
  public/pngs/thirdBadge.png
  public/webps/event_todaymung.webp
  public/webps/firstBadge.webp
  public/webps/thirdBadge.webp
  src/common/components/eventModal/eventContents.ts
  src/common/components/eventModal/index.styles.ts
  src/common/components/eventModal/index.tsx
  src/pages/todaymung/components/userInfo/index.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/todaymungWrite/queries/index.ts
  src/pages/todaymungWrite/types/index.type.ts
  src/service/apis/diary/index.ts
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: ✨ feat, 🔧fix, 🌱 env

#170 feat/SV-377: 이미지, 폰트 프리로딩, 레이지 로딩 적용 및 png -> webp 변경
  index.html
  package.json
  public/mockServiceWorker.js
  public/webps/LiedownDog.webp
  public/webps/StandBrownDog.webp
  public/webps/TodayMungLogo.webp
  src/common/components/noResultUI/index.tsx
  src/pages/detail/hooks/useScrollTop.ts
  src/pages/detail/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/index.tsx
  src/pages/main/styles/BottomSheet.style.ts
  src/pages/main/styles/index.style.ts
  src/pages/search/components/NoSearchResponse.tsx
  src/pages/todaymung/components/noDiaryList/index.tsx
  src/pages/todaymungEdit/index.tsx
  src/pages/todaymungPlaceRegist/components/SearchList.tsx
  src/pages/todaymungWrite/components/DogCard.tsx
  src/pages/todaymungWrite/index.tsx
  src/styles/GlobalStyles.ts
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#172 feat/SV-377: 상세페이지 동영상 엑박 수정
  src/pages/todaymungEdit/components/MediaGroup.tsx
  src/pages/todaymungWrite/components/MediaGroup.tsx
  tsconfig.app.tsbuildinfo
  yarn.lock
Labels: ✨ feat

#173 chore/SV-177: 오늘멍 조회 페이지 UI 수정사항 반영
  src/pages/todaymung/components/convert/index.tsx
  src/pages/todaymung/components/registButton/index.tsx
  src/pages/todaymung/components/todayMungCalendar/index.tsx
  src/pages/todaymung/components/userInfo/index.tsx
  src/pages/todaymung/styles/Convert.style.ts
  src/pages/todaymung/styles/TodayMungCalendarRoot.style.ts
  src/pages/todaymung/styles/TodayMungList.style.ts
  src/pages/todaymung/styles/UserInfo.style.ts
Labels: 👽 chore, 🔧fix

#176 fix/SV-384: bottomSheet 내부가 스크롤 안되는 버그 수정
  src/pages/main/hooks/useBottomSheet.ts
Labels: 🔧fix

#174 feat/SV-365: QA 사항 반영(대표 반려견 라벨 추가, 주소 입력 창에서 값이 수정되는 문제 해결, 생년월일 입력 문제 해결)
  src/pages/my/components/myDogs/index.tsx
  src/pages/my/components/profile/index.tsx
  src/pages/my/index.styles.ts
  src/pages/my/index.tsx
  src/pages/my/styles/profile.styles.ts
  src/pages/signUp/components/DatePicker.tsx
  src/pages/signUp/components/DaumPost.tsx
  src/pages/signUp/index.tsx
  src/pages/signUp/styles/daumPost.styles.ts
  src/pages/signUp/styles/signUp.styles.ts
  src/pages/todaymung/styles/UserInfo.style.ts
  src/pages/userEdit/index.tsx
Labels: ✨ feat, 🔧fix

#178 feat/SV-381: 시설 상세 시멘틱 태그 적용 및 documentTitle 구조 수정
  package.json
  src/App.tsx
  src/common/components/SEO/index.tsx
  src/common/hooks/useSetDocumentTitle.ts
  src/pages/detail/index.tsx
  src/pages/detail/styles/detail.styles.ts
  src/pages/detail/styles/todayMungCard.style.ts
  src/pages/dogEdit/index.tsx
  src/pages/dogs/index.tsx
  src/pages/login/index.tsx
  src/pages/main/components/bottomSheet/Content.tsx
  src/pages/main/components/bottomSheet/index.tsx
  src/pages/main/index.tsx
  src/pages/my/index.tsx
  src/pages/myFavorite/index.tsx
  src/pages/myReview/index.tsx
  src/pages/recommend/components/IndexGuest.tsx
  src/pages/recommend/components/IndexUser.tsx
  src/pages/search/index.tsx
  src/pages/signUp/index.tsx
  src/pages/todaymung/index.tsx
  src/pages/todaymungDetail/index.tsx
  src/pages/todaymungEdit/index.tsx
  src/pages/todaymungPlaceRegist/index.tsx
  src/pages/todaymungWrite/index.tsx
  src/pages/userEdit/index.tsx
  tsconfig.app.tsbuildinfo
  vite.config.ts
Labels: ✨ feat

#185 fix/SV-381: 모달 에러 수정
  index.html
  src/common/components/loginPromptModal/index.style.ts
  src/common/components/loginPromptModal/index.tsx
  src/common/components/modal/index.tsx
Labels: ✨ feat
